name: Build and Publish Docker Images

on:
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push v6 (Debian variants)
        uses: docker/build-push-action@v5
        with:
          context: docker
          platforms: linux/amd64,linux/arm64
          dockerfile: docker/debian/Dockerfile
          push: true
          tags: |
            phillarmonicsoftware/keydb:latest
            phillarmonicsoftware/keydb:6
            phillarmonicsoftware/keydb:6.3
            phillarmonicsoftware/keydb:6.3-bookworm
          build-args: |
            BRANCH=v6.3.4
            GOSU_VERSION=1.17

      - name: Build and push v6 (Alpine variants)
        uses: docker/build-push-action@v5
        with:
          context: docker
          platforms: linux/amd64,linux/arm64
          dockerfile: docker/alpine/Dockerfile
          push: true
          tags: |
            phillarmonicsoftware/keydb:6-alpine
            phillarmonicsoftware/keydb:6.3-alpine
          build-args: |
            BRANCH=v6.3.4
            GOSU_VERSION=1.17